### ISSUE TITLE
HTML formatting

### ISSUE THREAD

**Issue by cholek3** [jampez77/Multiline-Entity-Card#2]
Hello,

Great job with a card.

It would be even better :) if it supported html formatting, such as
- breaking lines: `\n` and/or `<p>text</p>`
- <b>bold:</b> `<b>text</b>`
- <i>italic:</i> `<i>text</i>`
- etc

Currently it looks like this:
![multi1](https://user-images.githubusercontent.com/43534386/127524593-536c303f-ce2b-48ca-9a54-15ee2358f591.jpg)

Formatting:
![multi2](https://user-images.githubusercontent.com/43534386/127524731-25b500f3-d86d-45a9-9459-64b7c7232f20.jpg)

Attribute in HA Developer Tools:
![multi3](https://user-images.githubusercontent.com/43534386/127524825-1d1ed35c-dbde-4704-b6d2-ab358368550b.jpg)

Regards

**Comment by jampez77** [comment]
Good idea! I will add this to my ToDo list :)

**Comment by jampez77** [comment]
Latest release now handles HTML formatting

https://github.com/jampez77/Multiline-Entity-Card/releases/tag/1.1.1

**Comment by cholek3** [comment]
B-E-A-utiful. Thanks so much.
