### ISSUE TITLE
Question about additional text formatting

### ISSUE THREAD

**Issue by nickh66** [jampez77/Multiline-Entity-Card#4]
Hi,
This is a great custom card but i was wondering if it might be possible to further alter the text displayed in the card.  For example, i would very much like to change the font size of the text displayed by the entity and/or included attribute.
So far i have played around with using options from [card-mod](https://github.com/thomasloven/lovelace-card-mod) but so far i can only change the font colour.
Is it possible to alter the font type/size in some way?
Regards
Nick

**Comment by jampez77** [comment]
Hi,

Thanks

You can indeed change the font using this card. The card parse HTML so you can use the `style` attribute on an element to achieve this.

There is an example here on how you'd do this: https://www.w3schools.com/html/html_styles.asp

Hope this helps.
