### ISSUE TITLE
Can you add tap_action?

### ISSUE THREAD

**Issue by pestregen** [jampez77/Multiline-Entity-Card#6]
Hi,
this card is very usefull for me, thanks for creating it!
Can you add tap_action to navigate to a different frontend-page by taping on it?

**Comment by jampez77** [comment]
Good idea, I shall add it to my Todo list.

**Comment by jampez77** [comment]
Sorry took me longer than I thought it would. I did the work over the weekend only forgot to commit it. Latest release should allow some `tap_actions`.

https://github.com/jampez77/Multiline-Entity-Card/releases/tag/1.2.0
